### ISSUE TITLE
The demo does not appear to work

### ISSUE THREAD

**Issue by damnMeddlingKid** [Ni55aN/D3-Node-editor#10]
Im on chrome `Version 59.0.3071.115 (Official Build) (64-bit)` and cant see anything in the demo for the editor.

i get this error in the console

```
pen.js:73 Uncaught TypeError: D3NE.NodeBuilder is not a constructor
    at pen.js:73:20
```

**Comment by Ni55aN** [comment]
Now it works. [The demo](https://codepen.io/Ni55aN/full/jBEKBQ/) has been updated
