### ISSUE TITLE
D3NE-examples/Angular doesn't work with 0.7.3.

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [Ni55aN/d3-node-editor#102]
Try change version from 0.6.11 to the latest 0.7.3 to check.
Looking in the source code I see that a lot of types have been changed since 0.6.11 which I'm using.
Would be nice to have it described in the docs or at least shown in the working example (Typescript)

Thanks!

**Comment by Ni55aN** [comment]
Yeah, it was `d.ts` typing errors. I'll publish last changes now

**Comment by Ni55aN** [comment]
https://github.com/Ni55aN/d3-node-editor/releases/tag/v0.7.4

**Comment by GeorgiyZhuravlev** [comment]
Thanks!
It works now.
