### ISSUE TITLE
Dynamic outputs

### ISSUE THREAD

**Issue by realTrueProger** [Ni55aN/d3-node-editor#106]
Hi, Ni55aN. Thx for cool lib!

I have a realy big trouble with it, hope you can help me)
I'am trying to create the dynamic add output functionality for the node(create new outputs by button click), something like this:

`editor.nodes[0].addOutput(new D3NE.Output("Number", numSocket));`

or more complex with new node method:

```
node.addOutput = () => {
            node.outputs.push(new D3NE.Output("Hit", actionSocket));
            node.outputs[node.outputs.length - 1].node = node;
            editor.view.update(); // need to run twice for connections view update
            editor.view.update();
        }
```

Then i add this action to node button event, everything looks to be working, but it creates problems with export/import: all new dynamically created outputs disappears after run editor.fromJSON attempt. Can you please give me some advise or ideas to make this work correctly?

**Comment by Ni55aN** [comment]
Hi @realTrueProger ! Thanks for watching, I'll take this into account when creating a new architecture

When creating node the builder must somehow know about the dynamic outputs. And by default, the data about really added outputs is not exported (and should not, because this should be handled by the builder)
`toJSON()`/`fromJSON()` itself only knows about the connections. Therefore, you can put information about outputs in the data property:
```js
node.addDynamicOutput = function(){
  this.addOutput(new D3NE.Output("Hit", actionSocket));
  this.data.meta = {dynOutputs: this.ouputs.length };
}
```

Thus, when importing a graph, the builder will know how many it should add outputs


```js
builder(node){
  for(let i = 0; i<node.data.meta.dynOutputs; i++)
  node.addOutput(new D3NE.Output("Hit", actionSocket)))

}
```

**Comment by realTrueProger** [comment]
This is great, thx! I was just thinking about something about node.data and check it in builder )))20.05.2018, 15:26, "Vitaliy Stoliarov" <notifications@github.com>:Hi @realTrueProger ! Thanks for watching, I'll take this into account when creating a new architecture
When creating node the builder must somehow know about the dynamic outputs. And by default, the data about really added outputs is not exported (and should not, because this should be handled by the builder)
toJSON()/fromJSON() itself only knows about the connections. Therefore, you can put information about outputs in the data property:
node.addDynamicOutput = function(){
  this.addOutput(new D3NE.Output("Hit", actionSocket));
  this.data.meta = {dynOutputs: this.ouputs.length };
}
Thus, when importing a graph, the builder will know how many it should add outputs
builder(node){
  for(let i = 0; i<node.data.meta.dynOutputs; i++)
  node.addOutput(new D3NE.Output("Hit", actionSocket)))

}
