### ISSUE TITLE
Problem with divs resizing

### ISSUE THREAD

**Issue by simplelike** [Ni55aN/d3-node-editor#108]
Hello. I am getting your example and try to use your library together with the jQuery lib, which makes divs resizeable, but have a little problem: resizing goes incorrect. Look: http://criptbook.myjino.ru/resize.html (left sidebar is resizeable). 
It was established that the problem appears at the time of contextMenu initialization:
`var menu = new D3NE.ContextMenu({
   Values: {
      Value: componentNum,
      Action: function() {
         alert("ok");
      }
   },
   Add: componentAdd
});`
In fact I dont need this ContextMenu in my project, but if i try to comment it, the editor initialization goes wrong.
`var editor = new D3NE.NodeEditor("demo@0.1.0", container, components, menu);`

Maybe you could help me to solve this problem?

**Comment by Ni55aN** [comment]
Try to wrap the  `<div id="nodeEditor" ... </div>` into a container

> It was established that the problem appears at the time of contextMenu initialization:

You can initialize an editor like this:
```js
var editor = new D3NE.NodeEditor("demo@0.1.0", container, components);
```

**Comment by simplelike** [comment]
It doesn't work unfortunately.
Such an editor initialization leads to error:

> Uncaught TypeError: Value of argument "menu" violates contract.
> Expected:
> ContextMenu
> 
> Got:
> void
>     at new NodeEditor (editor.js:16)

**Comment by Ni55aN** [comment]
What D3NE version are you using?

**Comment by simplelike** [comment]
Well, i'm including this scripts
```
    <script src="https://cdn.jsdelivr.net/npm/alight@0.14.0/alight.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3@4.10.2/build/d3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-node-editor@0.6.6/build/d3-node-editor.js"></script>
```

**Comment by Ni55aN** [comment]
Replace 0.6.6 to 0.7.4

**Comment by simplelike** [comment]
Well, it did not work either)
So maybe the problem is not in ContextMenu)
There are some another strange sympthoms: LeftMenus's default value is differs from its css value (in css: width = 300px vs 257px in fact). And Div#nodeEditor's width is set in 100% of my screen width, but it must be changed during the resizing. Looks like the default zoom out or smth like that.
Also there is an event listener on mouseMove for whole window. Maybe it's possible to change it only for Div#nodeEditor?

**Comment by Ni55aN** [comment]
Also try to set overflow: hidden on container and call `editor.view.resize()` while changing width of the left menu

**Comment by simplelike** [comment]
Thank you) That helped)
