### ISSUE TITLE
Default zoom level

### ISSUE THREAD

**Issue by JMidd91** [Ni55aN/d3-node-editor#110]
Hello,

Correct me if I am wrong, but in the [docs](https://d3-node-editor.readthedocs.io/en/latest/), I couldnt see anywhere that would inform me on how to set the zoom level by default / on load. is this even possible? if so how?

thanks a lot 👍

**Comment by Ni55aN** [comment]
```js
js editor.view.zoomAt(nodes); // Place the selected nodes in the field of view
/// or
editor.view.scale(k); // define the scale
```

**Comment by JMidd91** [comment]
perfect, thanks!
