### ISSUE TITLE
[FR] Nodes system back-end usage

### ISSUE THREAD

**Issue by trsh** [Ni55aN/d3-node-editor#112]
It's neat to play with nodes in front-end, but that's not 100% scenario. Sometimes you want to store some logic (flow), that is then used by back-end. And back-end is not always JavaScript.

I saw a back-end C lang https://github.com/Ni55aN/D3NE-engine, but that represents some problems.

1) You need to duplicate the workers logic in JS and C lang, what means there is lot of place to screw up.
2) I think the JSON, that is meant to recreate the Nodes in front-end is way to big and complicated for fast calculations on back-end that needs to deal only with inputs and outputs. 

Solution:

a) Think of an much primitive JSON, that only represents inputs and outputs, so it can be easy adopted by any programming language (PHP, Rust, Python). We can call it processing JSON. I will propose some structure soon. 

b) Implement JS workers as async, so I can call sockets, If that is my strategy to no duplicate the workers code. [check] (just checked, it's already like that?)

c) Or we can use WASM for serious languages (like C and RUST) for workers to not dupe the code.

**Comment by trsh** [comment]
Some pseudo JS:

```
    // JSON - in base there is output, as that is what we want in the end

    flow = outputs: {
      output1: {
        worker: 'worker1',
        wrokerType: 'globInput'
      },
      output2: {
        worker: 'worker1',
        wrokerType: 'globInput',
      }
      output3: {
        worker: 'worker2',
        wrokerType: 'input',
        inputs: [
          {
            //id: 'input1',
            from: 'output1'
          }            
          {
            //id: 'input2',
            from: 'output2'
          }            
        ]
      }
    }
    
    // Tarvesal

// startup, globInput defines non-node inputs, 
// like keyboard input, or data from database
    fn go(flow, globInput = {worker1: ...}){ 

      for(outId in flow){
        forOutput(outId, flow[outId], globInput);
      }
    }

    fn forOutput(outId, output, globInput){
      out = cache.getCalculatedResult(outId); // Look if it inst ready an cached

      if(!out && output.worker){ // Is not
        if(output.wrokerType.type == 'globInput'){
          out = output.worker(...globInput.worker1); // Woker takes global inputs
        }
        else if(output.wrokerType.type == 'input'){
          workerInputVals = [];
          for(input in inputs){ // Loops inputs
            outTmp = cache.getCalculatedResult(input.from); // Tries to get output from cache

            if(!ouTmp){ // No there, so we have to recurse
              outTmp = forOutput(input.from, flow[input.from], globInput);
            }

            workerInputVals.push(ouTmp); 
          }
          out = output.woker(workerInputVals); // call worker with all inputs (from outputs)
        }
      }
      cache.add(output.id, out); // Add to cache, to not repeat retrieval
    }
```

**Comment by trsh** [comment]
As you can see the JSON is super tiny, and so is the workers logic and so will be it's speed. It would be critical for robotics and other serious stuff, controller by Visual programming.

I could roll and PR (or create separate repo.), that converts Editor JSON, into this processing JSON, and also back-end code in Rust lang.

But let me know what you think @Ni55aN

**Comment by Ni55aN** [comment]
> that only represents inputs and outputs

 where will the data of the nodes be stored?

> Implement JS workers as async,

and make Socket requests to the server? Then there will be a big load on the server and slow processing on client

> Or we can use WASM for serious languages

this can be much more difficult if you have to write a lot of interaction in workers (on C, for example)

**Comment by Ni55aN** [comment]
> And back-end is not always JavaScript.

Any examples?

> It would be critical for robotics 

the main thing is performance? Then you can try to generate C code with the help of workers.
 In the new architecture, this can be added as a plugin, just let me finish work on this

**Comment by trsh** [comment]
> where will the data of the nodes be stored?

You still keep the editor JSON for storing nodes data and editor re-creation (there is no way around this), and the processing JSON (new one). For processing you **don't** care about node and groups, etc. For example, let's say you code some logic via nodes for robotic arm - that arm doesn't care about nodes, just about input and output, like 'move (x, y)'.

> and make Socket requests to the server? Then there will be a big load on the server and slow processing on client

Actually an open socket very, very fast. You can check some chat server-client examples. Anyway if a project requires such schema - "workers on back-end only, don't care about client speed to much as it's only for logic generation and saving it", it's a way to go. !Just an example.

> this can be much more difficult if you have to write a lot of interaction in workers (on C, for example)

Again, if a project is more back-end processing dependent, it's a way to go.

**Comment by trsh** [comment]
> Any examples?

My project back-end is on Rust lang, for example. I wan't to process nodes flow there.

> the main thing is performance? Then you can try to generate C code with the help of workers.
> In the new architecture, this can be added as a plugin, just let me finish work on this

Again, there is no way I can guarantee that the generated C code will act same as JavaScript that is fired on client side. It's duping code and sooner or later it goes wrong (as for example I can forget to edit both - js and C generator). So I want it the way around.

**Comment by trsh** [comment]
> ..this can be added as a plugin..

Yeah, sure. I will 100% go for sockets and that input-output JSON I presented above. So actually this doesn't present any FR for the original project. If it's useful, we can add it to some official plugin repo. So i'm closing this.
