### ISSUE TITLE
The process is busy...

### ISSUE THREAD

**Issue by Hatead1** [Ni55aN/d3-node-editor#164]
Example code (https://codepen.io/Ni55aN/pen/xzgQYq) on local without changes. When add new node "num" i get 1 warning (The process is busy... use abort()), when add node "Add" - 3 warnings.

**Comment by Hatead1** [comment]
And on codepen too...

**Comment by Hatead1** [comment]
engine/index.js
async process (.........) {

+	await this.abort();
        await this.processStartNode(startId);
}
В этом проблема или что-то еще может быть?

**Comment by Hatead1** [comment]
плюсик парсер скушал. Добавил аборт, предупреждение ушло.

**Comment by Hatead1** [comment]
не, не то, компоненты считать перестали :)

**Comment by Ni55aN** [comment]
This is due to `this.emitter.trigger ('process')` on Control, which is called at the same time as the event nodecreated (that is, not asynchronously)

**Comment by Ni55aN** [comment]
https://codepen.io/Ni55aN/pen/xzgQYq fixed by removing of `update()` inside `mounted()`
