### ISSUE TITLE
D3NE.Component is not a constructor

### ISSUE THREAD

**Issue by jcaffera42** [Ni55aN/D3-Node-Editor#27]
I'm getting 'ERROR TypeError: D3NE.Component is not a constructor' when I try to instantiate a D3NE.Component.

**Comment by Ni55aN** [comment]
It looks like you are not using the latest version

https://github.com/Ni55aN/D3-Node-Editor/releases/tag/v0.5.0
or
https://d3ne.surge.sh/node-editor.min.js

**Comment by jcaffera42** [comment]
My bad, it seems I had the previous version in browser's cache.
