### ISSUE TITLE
fromJSON() doesn't load values

### ISSUE THREAD

**Issue by Hamdiovish** [Ni55aN/d3-node-editor#30]
The method fromJSON() of the editor class doesn't load the value of the nodes, nodes take always the default values or "null".

Example based on the sample of the wiki:
The exported data using "editor.toJSON()":
> {"id":"demo@0.1.0","nodes":{"1":{"id":1,"data":{"num":**_10_**},"group":null,"inputs":[],"outputs":[{"connections":[{"node":3,"input":0}]}],"position":[80,200],"title":"Number"},"2":{"id":2,"data":{"num":**_10_**},"group":null,"inputs":[],"outputs":[{"connections":[{"node":3,"input":1}]}],"position":[80,400],"title":"Number"},"3":{"id":3,"data":{},"group":null,"inputs":[{"connections":[{"node":1,"output":0}]},{"connections":[{"node":2,"output":0}]}],"outputs":[{"connections":[]}],"position":[500,240],"title":"Add"}},"groups":{}}

but after calling "editor.fromJSON(data)", the **_10_** value is getting ignored and became **_1_**, the default value:
> {"id":"demo@0.1.0","nodes":{"1":{"id":1,"data":{"num":**_1_**},"group":null,"inputs":[],"outputs":[{"connections":[{"node":3,"input":0}]}],"position":[80,200],"title":"Number"},"2":{"id":2,"data":{"num":**_1_**},"group":null,"inputs":[],"outputs":[{"connections":[{"node":3,"input":1}]}],"position":[80,400],"title":"Number"},"3":{"id":3,"data":{},"group":null,"inputs":[{"connections":[{"node":1,"output":0}]},{"connections":[{"node":2,"output":0}]}],"outputs":[{"connections":[]}],"position":[500,240],"title":"Add"}},"groups":{}}

**Comment by Ni55aN** [comment]
It happened because the builder at import overwrites the data (since the builder is called when importing with fromJSON(), it decides what and how to write)

```js
var componentNum = new D3NE.Component("Number", {
  builder: function(node) { // here we get an instance of a node with "data":{"num":10}
    var numControl = new D3NE.Control('<input type="number" value="1">', ///  value is taken from here
         (el, c) => {
            function upd() { // this function put el.value to node.data.num
               c.putData("num", parseFloat(el.value));
            }

            el.addEventListener("input", upd);

            upd(); // it is necessary to rewrite the "num", because they may not be in data: {}
         }
      );
 ....
````
Here is what works correctly:
````js
var numControl = new D3NE.Control('<input type="number">',
     (el, c) => {
        el.value = c.getData('num') || 1; /// just write data.num to the <input>, otherwise "1" if data.num is null/undefined

         
        function upd() {
           c.putData("num", parseFloat(el.value));
        }

        el.addEventListener("input", upd);
        upd();
} );
````

[Updated sample](https://codepen.io/Ni55aN/pen/jBEKBQ?editors=0010)

**Comment by Hamdiovish** [comment]
Perfect!
thanks man
