### ISSUE TITLE
Is there any tips how to use this node editor with angular2?

### ISSUE THREAD

**Issue by andRave** [Ni55aN/d3-node-editor#31]
I can't use this lib with Angular2 project. Just because I have some problem with start.

**Comment by Ni55aN** [comment]
Can you provide more information about the errors that are displayed in the console, and have you linked external dependencies (D3.js and Angular light)?

**Comment by andRave** [comment]
If I linked external dependencies like this:
`import * as D3NE from '../../node_modules/d3-node-editor/build/d3-node-editor.js';
import * as D3 from '../../node_modules/d3/build/d3.js';
import * as Alight from '../../node_modules/alight/alight.js';`
It will be errors like this:
`ERROR in error TS5055: Cannot write file '/Users/andrave/Work/Projects/tests/node-editor/node_modules/alight/alight.js' because it would overwrite input file.
Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file '/Users/andrave/Work/Projects/tests/node-editor/node_modules/d3/build/d3.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.`

But if I wouldn't add d3 and alight dependencies, just d3NE, it will be an error d3 is not defined in console.

**Comment by Ni55aN** [comment]
Dependencies should be defined globally.
Try it:
```js
import * as d3 from 'd3';
import * as alight from 'alight';
window.d3 = d3;
window.alight = alight;
import * as D3NE from "d3-node-editor";
```

I'm slightly familiar with the  Angular2, and maybe there is a built-in ability to load dependencies globally. For example, webpack does it with ProvidePlugin

**Comment by PFight** [comment]
It is no need to import these files via `import` statement. Just add them as [global scripts](https://github.com/angular/angular-cli/wiki/stories-global-scripts).

**Comment by andRave** [comment]
Thanks.
