### ISSUE TITLE
Dependencies: Angular

### ISSUE THREAD

**Issue by D504** [Ni55aN/d3-node-editor#32]
I have found Angular in [the dependencies list](https://github.com/Ni55aN/D3-Node-Editor/wiki#dependencies). Are you sure?

**Comment by Ni55aN** [comment]
Yep! But this is not an `Angularjs`, which everyone knows, it's an `Angular light`. And it is needed in order to get rid of the painful update of data in the view manually. At least `D3.js` does not able to do it quickly with a minimum amount of code
