### ISSUE TITLE
Allow non-selected Control Click event

### ISSUE THREAD

**Issue by Eforen** [Ni55aN/d3-node-editor#33]
I am trying to find how this library suppresses the users click event on controls when the node is not selected I would like to be able to turn that feature off for some nodes so that the user can change inputs without needing to click the control 2 times

**Comment by Ni55aN** [comment]
Does the control element have an `mousedown` event handler with stopPropagation ?
```js
var numControl = new D3NE.Control('<input type="number">',(el,control)=>{
  //// ....
  el.addEventListener("mousedown", function(e){e.stopPropagation()});
});
```

**Comment by Eforen** [comment]
Wow derp... Thank you so much right on the money! In my haste to get going I commented out that line from the number example because I miss interpreted it... That's why you need to be careful programming while sleepy kids lolz! Thank you very much you and this project have really enabled me to hit the ground running this flow based hardware simulator I am making is almost done! Just got finish the save support and alow chips to be embedded in other chips and some other stuff and it's done!
