### ISSUE TITLE
How can I limit outputs to only one connection ?

### ISSUE THREAD

**Issue by Thomas-Negrault** [Ni55aN/d3-node-editor#35]
In the [wiki](https://github.com/Ni55aN/d3-node-editor/wiki/Nodes) you write:
> All outputs can have an unlimited number of connections. By default inputs can only have one connection. You can change this passing the third parameter as true

But in my case, I need to restrict an output to only one connection, can I do this ? Why does the output constructor does not have the `multiConns` param ?

**Comment by Ni55aN** [comment]
This is not provided in the library. Although it can be added in the next version.

On the other hand, it is easy to implement through events
```js
editor.eventListener.on("connectioncreate",(e) => {
    return e.output.node.title!=="Number" || e.output.connections.length==0; // when returns false, the connection will not be added

});
```
https://jsfiddle.net/Ni55aN/fazkp1hx/

**Comment by Thomas-Negrault** [comment]
The event listener is working but it will be for all of the nodes, or an ugly condition in the event listener in order to choose which nodes to impact. 

It works fine in my case so thank you !

 But yeah I think it could be usefull for a next version to be able to configure it during the output creation. In my case I am using your lib to create a bot script, and after a bot message there can only be one message

**Comment by Ni55aN** [comment]
@Thomas-Negrault in version 0.6.4, you can restrict an output to only one connection

```js
 new D3NE.Output("Number", numSocket, false);
```
https://jsfiddle.net/Ni55aN/fazkp1hx/4/
