### ISSUE TITLE
Problem trying to use this lib in TypeScript

### ISSUE THREAD

**Issue by Eforen** [Ni55aN/d3-node-editor#36]
The line 
```ts
import * as D3NE from 'd3-node-editor';
```
gives me the following error

Could not find a declaration file for module 'd3-node-editor'. '/node_modules/d3-node-editor/build/d3-node-editor.js' implicitly has an 'any' type.
  Try `npm install @types/d3-node-editor` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3-node-editor';`

**Comment by Ni55aN** [comment]
At the moment the library does not have a declaration file `.d.ts`. I will add it soon

**Comment by Ni55aN** [comment]
In what environment did you try to install it? In a simple example with a TypeScript without a file of declarations, I did not have such an error

**Comment by Ni55aN** [comment]
Added a file of declarations and made an[ example on Angular4](https://github.com/Ni55aN/D3NE-examples/tree/master/Angular4).

**Comment by Eforen** [comment]
I am using electron-forge and thus I am directly including it.

**Comment by Ni55aN** [comment]
Try to include the library and its dependencies globally (dependencies should in any case be globally). Also specify a reference to `d.ts`

**Comment by Ni55aN** [comment]
Is the problem resolved?
