### ISSUE TITLE
How to add node without using the context menu ?

### ISSUE THREAD

**Issue by Thomas-Negrault** [Ni55aN/d3-node-editor#38]
I need to have buttons that create node(s) in order to automate some process. After looking at the functions I found the `editor.addNode()` one that take a node in argument, and I have my component "myComponent" defined as the folowing:
```
    var myComponent = new D3NE.Component('My Component', {
        builder: function builder(node) {
            var input = new D3NE.Input('Dialog', dialogSocket, true);
            var output = new D3NE.Output('Dialog', dialogSocket, false);
            var questionControl = new D3NE.Control('<textarea rows="5"></textarea>', function (element, control) {
                element.value = control.getData('question') || '';
                control.putData('question', element.value);
                element.addEventListener('change', ()=> {
                    control.putData('question', element.value);
                });
            });

            node.addControl(questionControl);

            node.addOutput(output);
            node.addInput(input);

            return node;
        },
        worker: function worker(node, inputs, outputs) {
        }
    });
```

I want a button to add a node of myComponent. I've tried:

 ```
   d3.select('#addMyComponent').on('click', function () {
        editor.addNode(myComponent.newNode());
        editor.addNode(myComponent.builder());
    });
```
`myComponent.newNode()` add a node but without any output and without my textarea.

`myComponent.builder()` throw an error because it expect an input node...

How can I accomplish that ?

---
Edit: It seems to work (very slowly) with:
```
    d3.select('#addMyComponent').on('click', function () {
        editor.addNode(myComponent.builder(myComponent.newNode()));
    });
```
Is it the right way of doing it ?

**Comment by Ni55aN** [comment]
> Is it the right way of doing it ?

Yes, `component.newNode()` only creates a node with the component name, the builder does the rest.
It is necessary to first create a node with the required name, optionally specify data (as done in [fromJSON](https://github.com/Ni55aN/d3-node-editor/blob/master/src/node.js#L97) ), and then add inputs, outputs, etc.

**Comment by Thomas-Negrault** [comment]
Ok !
I thought it was slow but it is something else, when the editor is empty I need to move the mouse in order to see the new node. The node is created immediately (I listen to the nodecreate event) but it does not display in the editor until I move the cursor

**Comment by Ni55aN** [comment]
After adding a node, you must manually update the view
``` js
editor.view.update();
```

**Comment by manvfx** [comment]
problem in angular?

![1](https://user-images.githubusercontent.com/6747872/38233720-c19d1a3a-3730-11e8-8149-1ccc00a0298f.jpg)

my code:
```
addNode(){
    console.log('add');
    this.editor.addNode(this.componentSecond.builder(this.componentSecond.newNode()));
    this.editor.view.update();
  }
```

**Comment by Ni55aN** [comment]
@manvfx it seems like you forgot to pass the components to editor
```js
var components = [ this.componentSecond ];
var nodeEditor = new D3NE.NodeEditor('demo@0.1.0', container, components, menu);
```
