### ISSUE TITLE
Async Tasks Not working

### ISSUE THREAD

**Issue by CheweyZ** [Ni55aN/d3-node-editor#40]
Making an async task appears to make the resolving part not fire or react even though promise resolves correctly

```js
var componentDelayEvent = new D3NE.Component("Delay Event", {
  builder(node) {
    let act = new D3NE.Output("Action", actSocket),
        inp1 = new D3NE.Input("Action", actSocket)
    return node.addOutput(act).addInput(inp1);
  },
  worker(node, inputs, outputs) {
    var task = new D3NE.Task(inputs, async(inps) => {
      console.log("Resolve");
      await resolveAfter2Seconds()
      console.log("Should Pass");
      return [new D3NE.Task(inputs,(inps)=>{}).option(0)] //As need to return the option part as if return task.output below will fire on make
    })
    
    outputs[0] = task.output(0);
  }
});

function resolveAfter2Seconds() {
  return new Promise(resolve => {
    setTimeout(() => {
      console.log("Resolved");
      resolve('resolved');
    }, 2000);
  });
}
```

**Comment by CheweyZ** [comment]
Also have iteration of `    
let tempTask=new D3NE.Task(inputs,(inps)=>{})
var task = new D3NE.Task(inputs, async(inps) => {
      console.log("Resolve");
      await resolveAfter2Seconds()
      console.log("Should Send");
      // console.log(tempTask.option(0));
      return [tempTask.option(0)]
    })
  
    outputs[0] = task.output(0);
  }
});`

**Comment by Ni55aN** [comment]
async Tasks are not supported at this time. Action function you pass to Task is [calling without await ](https://github.com/Ni55aN/d3-node-editor/blob/master/src/extras/task.js#L40). Therefore the following nodes are executed without waiting for the current one to done. 
I'll take care of this at evening.

One more thing, why are you passing on `tempTask.option(0)` inside another task ? Worker should have one task. `option(index)/output(index)` shouldn't refer to same output's index

**Comment by CheweyZ** [comment]
This is what i originally had but the issue was it would immediately pass even before promise had resolved
```js
var componentDelayEvent = new D3NE.Component("Delay Event", {
  builder(node) {
    let act = new D3NE.Output("Action", actSocket),
        inp1 = new D3NE.Input("Action", actSocket)
    return node.addOutput(act).addInput(inp1);
  },
  worker(node, inputs, outputs) {
    var task = new D3NE.Task(inputs, async(inps) => {
      console.log("Resolve");
      await resolveAfter2Seconds()
      console.log("Should Send");
    })
    
    outputs[0] = task.option(0);
  }
});
```

**Comment by Ni55aN** [comment]
@CheweyZ new version [v0.6.8 ](https://github.com/Ni55aN/d3-node-editor/releases/tag/v0.6.8) has been released with async Tasks
[Example](https://cdn.jsdelivr.net/npm/d3-node-editor@0.6.7/build/index.html) of use

**Comment by CheweyZ** [comment]
Thanks so much for fast fix and reply

**Comment by CheweyZ** [comment]
Another thing should maybe open another issue but the link https://github.com/Ni55aN/d3-node-editor/wiki/Tasks/#tasks   found on https://github.com/Ni55aN/d3-node-editor/wiki/Engine Just takes you back to base wiki url is this intended?

**Comment by Ni55aN** [comment]
I have not filled out the page on wiki for this object yet. I'll deal with this a little later
