### ISSUE TITLE
JSON Format for Editor

### ISSUE THREAD

**Issue by andyhoyle** [Ni55aN/d3-node-editor#41]
Nodes is not an array. As a result, when trying to programatically generate JSON, manual editing of the produced JSON is required:

`{  
   "id":"demo@0.1.0",
   "nodes":[  
       {  
         "id":1,
         "data":{"num":1},
         "group":null,
         "inputs":[],
         "outputs":[  
            {"connections":[  
                  {"node":3, "input":0 }
            ]}
         ],
         "position":[ 80, 200 ],
         "title":"Number"
      }
   ],
   "groups":{ }
}`

Needs changing to:
`{  
   "id":"demo@0.1.0",
   "nodes":{  
      "1":{  
         "id":1,
         "data":{"num":1},
         "group":null,
         "inputs":[],
         "outputs":[  
            {"connections":[  
                  {"node":3, "input":0 }
            ]}
         ],
         "position":[ 80, 200 ],
         "title":"Number"
      }
   },
   "groups":{ }
}`

**Comment by Ni55aN** [comment]
Try it:
```js
var dataArr = { "id":"demo@0.1.0", "nodes":[ { "id":1, "data":{"num":1}, "group":null, "inputs":[], "outputs":[ {"connections":[ {"node":3, "input":0 } ]} ], "position":[ 80, 200 ], "title":"Number" } ], "groups":{ } };

let arr2obj = arr => {
    var nodesObj = {};
    arr.forEach(node => nodesObj[node.id]=node);
    return nodesObj;
}

var dataObj = {id: dataArr.id, nodes: arr2obj(dataArr.nodes), groups: dataArr.groups};
```

**Comment by andyhoyle** [comment]
Great, that worked, thanks. I seem to have misinterpreted the JSON loader. I am trying to create a diagram from scratch. That includes creating the components and sockets from scratch. The source data is created by parsing source code using Roslyn. Is there a way to generate the components and sockets form JSON? Thanks.

**Comment by Ni55aN** [comment]
Components and sockets creates only programmically while JSON stores information about instances of nodes and their connections.

You can generate components and sockets from JSON, but this should not be the data presented above. 
What exactly do you want to do? What do you get from Roslyn?

**Comment by andyhoyle** [comment]
The goal is to document a CQRS based Actor system. A command raises an event, which in turn can call other commands (indirectly). By using Roslyn to walk all actors and create each one as a component, adding each Command as an Input and each Event as an output, I can use the node editor to draw this.

I have output the data in JSON format, then iterate it to create components with the correct inputs and outputs. I then iterate again to generate the connections. This is all working fine now. I have also used groups to logically group together related actors.

The challenge I now have is placement. I'd like to use something like this to solve the issue but not sure if the D3 API is visible from the D3NE objects: http://marvl.infotech.monash.edu/webcola/examples/smallgroups.html

**Comment by andyhoyle** [comment]
Also do you see a way, using the current functionality, to optionally map an input to on or more outputs (using a connecting line)?

**Comment by Ni55aN** [comment]
What is wrong with a placement? If you mean overlapping nodes on each other, to prevent this there is no built-in method. You need to manually calculate the position of the nodes based on already occupied areas (as done with the groups in your example)

**Comment by Ni55aN** [comment]
Input can easily have multiple connections. Maybe, for your example can be done as follows:
var connections = JSON.parse("[{\"SourceActor\":4,\"DestinationActor\":3,\"SourceOutput\":0,\"DestinationInput\":0},{\"SourceActor\":4,\"DestinationActor\":3,\"SourceOutput\":1,\"DestinationInput\":0},{\"SourceActor\":4,\"DestinationActor\":3,\"SourceOutput\":2,\"DestinationInput\":0}]");

On the other hand, scene have to many nodes with very large number of inputs/outputs. Most likely it should not be so.

**Comment by kamil-zielinski** [comment]
@Ni55aN 
[Here](https://github.com/retejs/rete/issues/41#issuecomment-358091938) you write that it's possible to create sockets programmatically. How to do it, to make `editor.fromJSON` create the whole graph with connections?
I know that sockets can be created with `new Rete.Socket('Number');` but where to assign sockets?
Currently, I have an error  `rete.esm.js:580 Error: Socket not fount for Number with key num`.

**Comment by Ni55aN** [comment]
> Currently, I have an error 

Seems like in `builder()` there is no input/output added to node

> How to do it, to make editor.fromJSON create the whole graph with connections?

The node is configured in the builder method of each component, there you can pass the data and add inputs / outputs and controls to the node based on this data.

For example:

```js
class MyComponent extends Rete.Component {
    constructor(nodeFactory) {
        this.nodeFactory = nodeFactory;
    }
    builder(node) {
        this.nodeFactory.modifyNode(node);
    }
}

class NodeFactory {
    setDate(data) { // data received from a server
       this.data = data;
        this.sockets = // generate sockets based on data
    }

    modifyNode(node) {
        const inputs = // generate an inputs based on data
        inputs.forEach(i => node.addInput(i))
    }
}
```

**Comment by kamil-zielinski** [comment]
Ok, so it seems like I can build a graph creating nodes an inputs myself. I thought that it might be possible to create a whole graph just based on JSON data using the editor `fromJSON` method.

Thank you for your answer.
