### ISSUE TITLE
First-class support for groups

### ISSUE THREAD

**Issue by niemeyer** [Ni55aN/d3-node-editor#42]
Thanks for working on this. I've been thinking about something along those lines for a while. It's great to see it materialized.

Do you plan to support some sort of first-class group concept, similar to what Blender offers, so one might just select a few nodes, mark them as a group, and make them expand and collapse as needed?

**Comment by Ni55aN** [comment]
Do you mean something like that ?
![](https://code.blender.org/wp-content/uploads/2012/01/node_group_interface9.png)

Or simple frame with possibility to expand and collapse? Perhaps just hiding the nodes will not be useful if there are too many nodes in the scene. Most likely it's better to use [modules](https://codepen.io/Ni55aN/pen/QOEbEW)

At present time you can add multiple nodes to group (Ctrl+LMB -> G)
