### ISSUE TITLE
Multi depth menu

### ISSUE THREAD

**Issue by CheweyZ** [Ni55aN/d3-node-editor#44]
Issue being when there renders on the second tab going into third it just displays label and no further popout
```js
new D3NE.ContextMenu({
  'top': {
    'first': onFirstEvent,
   'Second parent':{
          'three deep': something //this wont show
  }
}
})
```

**Comment by Ni55aN** [comment]
Context menu doesn't support more than one level nested lists.  It is more difficult for the user to find desired item in deeply nested lists. 
But you can use third-party context menu and create nodes programically as follows:
````js
var node = component1.newNode();
component1.builder(node);
editor.addNode(node);
````
https://github.com/Ni55aN/d3-node-editor/issues/38
