### ISSUE TITLE
EventListener's handler has no parameters

### ISSUE THREAD

**Issue by vic29** [Ni55aN/d3-node-editor#46]
This code example from wiki page is not working, gives compile error on Angular 5 for me.

`editor.eventListener.on('nodecreate', (node, persistent) => { 
   // trigger after each of the first six events

   /// check if there is already a node with that name
  var haveSomeNode = editor.nodes.some(item => item.name === node.name); 
  return !haveSomeNode; // prevent the addition of a new node
});`

Handler's declaration not allows parameters but it will be very useful if we could do something with the newly created, selected, etc. node.

**Comment by Ni55aN** [comment]
It seems that need to override the method in the declaration file. Try to set the following
```js
namespace D3NE {
class EventListener {
    private events: Object;
    persistent: boolean;

    constructor();
    on(names: string, handler: (param?: any, persistent?: boolean) => any): EventListener;
    trigger(name: string, param?: any): any;
  }
}
```

**Comment by valefix80** [comment]
Hi,

I am runnnig in the same problem... can you please explain a bit more how to solve the problem?

thank you

**Comment by vic29** [comment]
Create a copy from the namespace declaration file (../../../node_modules/d3-node-editor/src/index.d.ts) into your project's directory. 
Find Eventlistener and replace its code with the above.
Save your file and use it from your angular module (instead of the default index.d.ts):
/// <reference path="my-node-editor/src/my_index.d.ts"/>

**Comment by valefix80** [comment]
thank you!

**Comment by Ni55aN** [comment]
Oh, I will  update .d.ts in new release

**Comment by Ni55aN** [comment]
New release is here: https://github.com/Ni55aN/d3-node-editor/releases/tag/v0.6.9
