### ISSUE TITLE
Is there a copy feature for groups or nodes?

### ISSUE THREAD

**Issue by Linkupdated** [Ni55aN/d3-node-editor#48]
I would like to know if there is a copy feature or an api to copy nodes or groups?

If not maybe pointing me in the right direction could help.

thanks!

**Comment by Ni55aN** [comment]
Try following
```
var groupCopy = D3NE.Group.fromJSON(group.toJSON())
var nodeCopy = D3NE.Node.fromJSON(nodeComponent, node.toJSON())
```

**Comment by Linkupdated** [comment]
I just tried but since the Id is the same it doesn't seem to duplicate correctly

`var node = component.newNode();
component.builder(node);

node.position[0] = json.position[0]-100;
node.position[1] = json.position[1]-100;

node.data = json.data;
editor.addNode(node);`

This one seem to work but the data in D3NE.Control when I save with editor.toJSON() seem to copy the same data. Even if they are not the same value when exporting. I can't figure out yet why its doing that.

**Comment by Linkupdated** [comment]
I was able to figure out the problem for anyone interested.

I needed to do a deep copy of the `json.data` object.

```javascript
node.data = json.data;
```

I found a deep clone function that seem to works for the task

```javascript
function clone(obj) {
				if (obj === null || typeof(obj) !== "object" || "isActiveClone" in obj)
					return obj;

				if (obj instanceof Date)
					var temp = new obj.constructor(); //or new Date(obj);
				else
					var temp = obj.constructor();

				for (var key in obj) {
					if (Object.prototype.hasOwnProperty.call(obj, key)) {
						obj["isActiveClone"] = null;
						temp[key] = clone(obj[key]);
						delete obj["isActiveClone"];
					}
				}

				return temp;
			}
```

**Comment by Ni55aN** [comment]
Sorry, fromJSON is `async`, and you are right - IDs is equal

It seems that the nodes are accessing the same data object
Try deep copying 
https://www.npmjs.com/package/deepcopy

```js
node.data = deepcopy(json.data);
```

**Comment by Ni55aN** [comment]
Hah.. ahead of me
