### ISSUE TITLE
How can I know the index of the current node?

### ISSUE THREAD

**Issue by sasmaster** [Ni55aN/d3-node-editor#50]
Let's say I have got 5 nodes connected  linearly in chain. How can I know from within each node its index in the chain?
Sorry for asking it here,I didn't find anything related to it in the docs.

**Comment by Ni55aN** [comment]
Can you describe the problem in more detail, exactly, for what you need to get indexes?

**Comment by Ni55aN** [comment]
A quick solution is to make the increment of the global variable in the workers, and before calling the process() to reset this variable

**Comment by sasmaster** [comment]
The problem is simple: I have a several nodes connected one with another like a chain. I want to know the ordered of the connected nodes. I see the editor keeps track of all the nodes,but as added nodes.It doesn't keep them necessarily in the order in which they're connected.

**Comment by Ni55aN** [comment]
The nodes are processed according to the principle from left to right. The leftmost will be processed first, and the last will be the latest on the right.
First of all:
`new D3NE.Node()` it is instance of node in editor
`node` parameter in worker it is data of instance. I.e result of `editor.nodes[0].toJSON()`

Do you always have nodes that are connected only in a chain? What is the main task?
Maybe it's directly related to your task https://github.com/Ni55aN/d3-node-editor/issues/52#issuecomment-369727350
