### ISSUE TITLE
Styling docs are not clear

### ISSUE THREAD

**Issue by sasmaster** [Ni55aN/d3-node-editor#51]
Hi,I am sorry, but what is ".node.title-of-node" .I mean what is "title-of-node"? Where do I set/find it?

Thanks.

**Comment by Ni55aN** [comment]
You define it in the first parameter when creating a Component
```js
new D3NE.Component("My node", ..
```

then, style selector should be (transformed to kebab case)
```css
.node.my-node
```
![2018-03-01_001800_codepen io](https://user-images.githubusercontent.com/8259641/36816390-3fcfaebe-1ce6-11e8-867f-ac6ca39335ee.png)

**Comment by sasmaster** [comment]
Here we go! Thanks for clarification!
