### ISSUE TITLE
How to retrieve the accumulated data from the last node?

### ISSUE THREAD

**Issue by sasmaster** [Ni55aN/d3-node-editor#52]
Hi. I am sorry for nudging ,but the examples for this lib are really basic.It is hard figure out a lot of real world functionality. For example, I have the following case.I have a a sequence of nodes. All the nodes are of the same component type.Each one connection only with one node at the right. Chain like composition,all right.Each node holds a string.When  a node gets connected with another node from the left,it concatenates left's node string with its own string and puts it into outputs[0] ,which is string. So I expect,somehow ,to be able to get the long string of all the string from all the nodes at the last node.But it doesn't work. Worker of the node component does this:

     ```
   worker(node, inputs, outputs)
      {
        outputs[0] = inputs[0] +"," + node.data.fname;
      }
```

And I am trying to get the final string at the last node like this:

 ```
    editor.eventListener.on("change", async function()
   {
     await engine.abort();
     await engine.process(editor.toJSON());
     console.log("Num connected nodes:" + editor.nodes.length);
     console.log("Files:" + editor.nodes[editor.nodes.length -1].outputs[0]);
  });
```

But it shows some [Object] thing,That's it.I have been also trying to debug the editor object in the chrome debugger and when inspecting every node object stored in the editor,I don't see any reference to the values from the previous nodes.Also,the worker function does spit the accumulated value,but it does so even if the nodes are not connected,but just are thrown at the scene.So either I am missing something bug,or something wrong with the lib. The docs are very poor. I mean,I am completely fine with supporting this project at patreon or something,but it's hard to understand even how to use this lib at the very basic level.

**Comment by GeorgiyZhuravlev** [comment]
[in the example](https://codepen.io/Ni55aN/pen/jBEKBQ) (`componentAdd > worker`) `inputs[0][0]` used to get input value.
(Don't ask me why the input is an array of arrays, I don't know)

**Comment by Ni55aN** [comment]
Yes, it is true. `inputs` argument in `worker()` is array because in general one input can accept multiple connections (outputs from connected nodes)

https://jsfiddle.net/Ni55aN/7ns6srnd/1/
![opera _2018-03-01_004019_jsfiddle net](https://user-images.githubusercontent.com/8259641/36817456-e4b59d46-1ce9-11e8-99ee-4b4518370cbf.png)

**Comment by Ni55aN** [comment]
To get the result, you must have a special node that will accept it. Then in the correspond Component worker you can get your result (inputs[0][0])

**Comment by sasmaster** [comment]
You see,I thought about that thing (having a special 'closing' node). But that means,I must force users using that node.That presents UX inflexibility. What I would really want is to be able to know which node is the last one in the chain of connected nodes.

**Comment by sasmaster** [comment]
> To get the result, you must have a special node that will accept it. Then in the correspond Component worker you can get your result (inputs[0][0])

And how can I get the results not from the worker,but let's say, from the node directly?
Something like this doesn't work:

editor.eventListener.on("change", async function()
{
   await engine.abort();
   await engine.process(editor.toJSON());
   console.log("All strings:" + endNode.inputs[0][0]);
});

**Comment by Ni55aN** [comment]
Ok, then you can change the data in the global variable from the worker or pass the object to the `process() `and change his data from the worker. https://jsfiddle.net/Ni55aN/bhmotaox/13/ (look at the result in console)

```js
worker(node, inputs, outputs, accumulator) {
      outputs[0] = inputs[0][0] + 1;
      accumulator.number = outputs[0];
   }
```

```js
   var accumulator = {number: 0}
   await engine.process(editor.toJSON(), null, accumulator);
   console.log(accumulator)
```

It will work if the nodes are in the chain. But you can get the wrong data if not all nodes are connected together. Then you get the data simply from the last processed node, even if it does not relate to the main nodes
![2018-03-01 22-51-39](https://user-images.githubusercontent.com/8259641/36869121-4e958460-1da3-11e8-87e9-1e1b49d763e3.png)
![2018-03-01 22-51-57](https://user-images.githubusercontent.com/8259641/36869125-50ccff2e-1da3-11e8-8c91-de669f63d21d.png)
