### ISSUE TITLE
Overriding this.default.onClick in ContextMenu

### ISSUE THREAD

**Issue by Linkupdated** [Ni55aN/d3-node-editor#53]
Sorry again for disturbing, i am currently trying to override the click event on the context menu with
```javascript
this.default.onClick = async (item) => { 
```
in the constructor of ContextMenu

But assignContextMenuHandler() in editorView is executed in areaClick() so it is always overriden

When I comment that line out it works. I am wrong, is there another way to override it?

Thanks!

**Comment by Ni55aN** [comment]
onClick is triggered when you click on item in context menu. Do you really need this, or do you want to override click on area?
