### ISSUE TITLE
Adding labels to controls

### ISSUE THREAD

**Issue by fschutt** [Ni55aN/d3-node-editor#54]
I tried adding labels to a control, but that prevents the event handler from firing.

```js
let north_ctrl = new d3ne.Control('<label>North</label><input type="number">',
    (element, control) => {
        element.addEventListener('keyup',()=>{
            control.putData('north', parseFloat(element.value));
        });
    });
```

This doesn't fire when I input a number into the field. I can make it work by removing the label:

```js
let north_ctrl = new d3ne.Control('<input type="number">',
    (element, control) => {
        element.addEventListener('keyup',()=>{
            control.putData('north', parseFloat(element.value));
        });
    });
```

... but with multiple fields I can't distinguish what number should go where. Is there a "label" property for fields? How can I add a label for a control (input field or checkbox) like in the following picture and have the callback working properly?

![layers](https://user-images.githubusercontent.com/12084016/36842737-e51c645a-1d4c-11e8-82af-85154adaa590.png)

**Comment by fschutt** [comment]
It seems that D3NE applies the event listener to the first element it sees, in this case the `label`. Since a `label` doesn't have an `onkeyup` event, it never fires. I can make if work by reversing the order (`<input type="number"><label>North</label>`, and then using CSS to reverse the visual order. However, this is a **very hacky way** of doing things.

**Comment by Ni55aN** [comment]
Put your label and input into a container
```html
<div class="container"><label ... ><input/></div>
```

Then:
var input = element.querySelector('input')
