### ISSUE TITLE
feature: get/set default node template

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [Ni55aN/d3-node-editor#55]
Not a vital thing to have, of course, but would be nice to have.
For now, to get default node template it is necessary to do something like this:
```
    const stub = new D3NE.Component('', {
      builder() {},
      worker() {}
    });
    nodeTemplate = stub.template;
```
Which then (if modified e.g. with regex, to extend with `data` specific markup) has to be explicitly specified for every new component via `props` `template` member.
Would be great to just `getDefaultNodeTemplate()` and `setDefaultNodeTemplate()` 
(or something like this).

**Comment by Ni55aN** [comment]
Why do you need to get a standard template at runtime? This can lead to some errors and an non-obvious result.
In my opinion the most convenient and reliable option is to predefine your template based on [this](https://github.com/Ni55aN/d3-node-editor/blob/master/src/templates/node.pug) (in html, of couse)
