### ISSUE TITLE
Components softlocking when making a wrong connection.

### ISSUE THREAD

**Issue by Trashtalk217** [Ni55aN/d3-node-editor#56]
### The bug:
Components are softlocking (not updating) when wrong connections are made. This persists after you've fixed the wires.

### Reproduce the bug:
1. Open Flow-based programming example (https://codepen.io/Ni55aN/pen/jBEKBQ)
2. Connect the output from 'Add' to one of the inputs from 'Add'. This is a wrong connection it shouldn't do anything.
3. Repair the connection you just broke. You should be left with what you started with.

Now the 'Add' component is softlocked in doesn't respond to any changes in both inputs. The number three will stay on the 'Add' display and whatever you do with the wires it stays broken. The only fix is reloading the page, since replacing it doesn't work. I haven't been able to create any working 'Add' Components after that.

**Comment by Ni55aN** [comment]
Thanks, I'll fix it

**Comment by Trashtalk217** [comment]
Glad I could help, I'm looking to contribute to this project so I'll keep looking for more bugs and maybe do some documentation.

**Comment by Ni55aN** [comment]
Thanks so much!

**Comment by Ni55aN** [comment]
[Fixed!](https://codepen.io/Ni55aN/pen/jBEKBQ)
