### ISSUE TITLE
newly generated node Ids don't match JSON id; problem for adding connections dynamically

### ISSUE THREAD

**Issue by sarora2073** [Ni55aN/d3-node-editor#57]
Hi,

Thanks for creating and sharing this awesome library!

I tried to recreate the connections dynamically based off the JSON export object (couldn't find any code for that so figured I'd try it myself), and noticed that the ID I pass from the JSON isn't the ID for the new node. 

Since I rely on the IDs from the JSON source to match the node ID when creating connections, this mismatch between the IDs makes recreating the connections unreliable.

I dug into the block.js file and found that in fact the code creates a self-incrementing numeric ID when a new Node is created.

This is brittle for several reasons:

1. imagine i create 10 nodes, but then delete the one with ID 7, then save the JSON, and reload. The JSON IDs will no longer match the IDs in the nodes array.

2. Numeric IDs get converted to string when stored and retrieved. When I tried to compare the JSON ID to the node ID, I was getting errors because I had to cast the retrieved ID to a numeric first, to get it to match the node ID.

Suggested Improvements:

1. When creating a new Node, the ID in the JSON (string) should be used by default, not a self-incrementing number.

2. block.js should use a library like uuid to create a unique ID for all new nodes (create in the UI).

Please let me know if this sounds like the right direction. Glad to do a PR.

Best Regards,

-S. Arora

**Comment by Ni55aN** [comment]
Can you provide an example on jsfiddle ?

> noticed that the ID I pass from the JSON isn't the ID for the new node.

During importing from JSON, node IDs are [replaced with actual IDs](https://github.com/Ni55aN/d3-node-editor/blob/master/src/node.js#L100) from the data. Instances of the created nodes will have the same ID as in the data.

> Numeric IDs get converted to string when stored and retrieved

Where do you store them? `JSON.parse(JSON.stringify(data))` returns numberic IDs

**Comment by sarora2073** [comment]
Hi,

Appreciate the quick response! 

It's not a running example, but I've copy / pasted relevant snippets here: https://jsfiddle.net/sarora/ar0kn5sh/7/

- lines 88 - 100 show the main section where i'm building the connections from the JSON. Maybe I shouldn't be doing it this way??
- on line 93 you can see where I have to cast the id to numeric otherwise the JSON version taken as-is is a string. 

re: the fromJSON method you pointed out...is that something I'm supposed to invoke directly? In line 81 i create the push the generated node to an array of nodes, but don't do anything else fancy as you can see.

Thanks again,

-S. Arora

**Comment by Ni55aN** [comment]
Starting at line 45: you shouldn't generate data based components. 
Declared components are executable code that describes the behavior of your editor for a particular version. 
Data only stores information about a user-created graph. Data is always dependent on components, but components shouldn't depend on data.

Can you describe your main goal?
Later I will try to describe in the visual representation the concept of this library

**Comment by sarora2073** [comment]
My overall goal is to allow users to create diagrams. Their might perhaps
10 components that can be built statically if need be..I haven’t really
started working on that part yet so was mainly using sample code for
component generation. Once a user creates a diagram I need to be able to
regenerate the diagram and allow users to modify / re-save the diagram
reliably.

**Comment by sarora2073** [comment]
Did a little more digging and found how to invoke fromJSON method when instantiating the editor in this example: https://codepen.io/Ni55aN/pen/POWEvm?editors=1010 

Will try this approach and close case if it works. 

I'm still not a fan of the numeric / auto-incrementing ID due to other bug risks mentioned, but that may be a "nice to improve" item at this point. Thanks again for everything!

**Comment by sarora2073** [comment]
Thanks for pointing me in the right direction..fromJSON imported the data and setup the connections.
