### ISSUE TITLE
Make a node without popup menu

### ISSUE THREAD

**Issue by leshiysoft** [Ni55aN/d3-node-editor#59]
Hi. Is it possible to make a node in a different way than using a popup menu, for example by an outside menu. If it is possible I want to now what a function/functions should be called to make a node.

**Comment by Ni55aN** [comment]
Hi!
https://github.com/Ni55aN/d3-node-editor/issues/38

**Comment by leshiysoft** [comment]
Thank you! I should have studied the history of the issues. Sorry :-)
