### ISSUE TITLE
Values getting clipped

### ISSUE THREAD

**Issue by CheweyZ** [Ni55aN/d3-node-editor#60]
This code used to work but I'm guessing in a recent update something has broke?

So the issue is I've got a block that outputs a string which is found however the block receiving it only get the very first character
```js
  worker(node, inputs, outputs) {
    var task = new D3NE.Task(inputs, (inps) => {
      let arr = inps[0] ? inps[0][0] : 0 
      let index = inps[1] ? inps[1][0] : 0 
      console.log(arr[index]);
      console.log(typeof(arr[index]));
      return (arr[index])? arr[index]:"Undefined"
    });
    outputs[0] = task.option(0);
    outputs[1] = task.output(0)
  }
```
This is the worker of the sending block
which has the console log output of
```
{"username":"Chewey","id":"1234","discriminator":"1234","avatar":null}
string
```
Yes it is JSON but its in string format as shown by the type of so this means should be parsed as a string and treated like one however the recieving block
```js
  worker(node, inputs, outputs) {
    var task = new D3NE.Task(inputs, (inps) => {
      let member = inps[0] ? inps[0][0] : "" 
      console.log(inps);
// clipped off rest as theres a bit
```
this will output 
![image](https://user-images.githubusercontent.com/19643053/37560571-eb71d29e-2a9f-11e8-82a3-494794459f0b.png) which shows really how the string has been cliped and is not been put into another input or anything

Any ideas or reasons as to why this could happen?

(also please remove the console log from line 172 of engine it's really annoying)

**Comment by Ni55aN** [comment]
It is difficult to find out where the data could have changed. I need a living example of your implementation

**Comment by Ni55aN** [comment]
Closed due to inactivity
