### ISSUE TITLE
How to save graph?

### ISSUE THREAD

**Issue by manvfx** [Ni55aN/d3-node-editor#62]
how to save D3-Node-Editor graph in database or save in rest api?
or 
how to save json from D3-Node-Editor?

Note: with angular

**Comment by Ni55aN** [comment]
```js
var graphData = editor.toJSON(); //save
 
editor.fromJSON(graphData); //restore
```
https://github.com/Ni55aN/d3-node-editor/wiki/Editor#exportimport-data

**Comment by manvfx** [comment]
thanks a lot
good work
