### ISSUE TITLE
how to implement repeater (trigger next node worker multiply times)

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [Ni55aN/d3-node-editor#65]
Hi!
Please check the graph:
![image](https://user-images.githubusercontent.com/14068189/38273925-e1311a08-3795-11e8-9c4b-042d1e4938bb.png)
I have a `Link` node which gets some collection and among other things fills `Entities` output with the array of some entities. And I have an `Action` node which represents an action that can be called for a particular entity (only one, normally its "Actions" input is filled by another type of node - conditional `Picker`, which in its turn finds an entity with given conditions and splits it to a set of outputs).

The question is: how can I "trigger" event of changing `Repeater`'s output to allow `Action` do its work as many times as many entities were given (to start its `worker` function for every entity)?

I've tried this approach...
```javascript
      // Repeater worker
      async worker(node, inputs, outputs) {
        const entities = inputs[0][0];
        const delayedOutput = (entity) => {
          return new Promise(resolve => {
            setTimeout(() => resolve(outputs[0] = entity), 1000);
          });
        };
        await delayedOutput(entities[0]);
        await delayedOutput(entities[1]);
        // loop will be used instead...
      }
```
... which obviously doesn't do what I need since `Action` gets only the last value (and it is normal behaviour, I understand).

But how then can I get this done?
(entities array is not async but the `Action` worker is async, if it matters)

**Comment by Ni55aN** [comment]
The main thing is that you can not call out the same node many times.
I do not know exactly how this would work, but most likely this will lead to unpredictable behavior.

The Action node can process an array of entries at a time

**Comment by GeorgiyZhuravlev** [comment]
> The Action node can process an array of entries at a time

Of course, but the result (output) of such processing will be "one thing" (array or "reduce"-d value from the array). And it means that all the following nodes in a chain must be able to work with the array of values - not a single value.

Probably I haven't explained the case well enough. Please, check the graphs:

<img width="956" alt="aaaaa" src="https://user-images.githubusercontent.com/14068189/38366109-72b13b0a-38e7-11e8-8485-296408293e37.png">

1 group of connected nodes shows what I already have: node of type "Entity Picker" take the entity from the previous node's array (matching search conditions) and pass it to further processing.
So all nodes are "one value"-aware as for their `inputs`.

2 group is what I intended to have. Instead picker - repeater. So for all the following noded nothing changed - they always get "one value", but they just get in many times :)

The way you proposed ("array-ready" nodes) can be an option. The only confusing thing is that error handling would be way harder to implement and also the fact that all nodes in a chain would report once for all.

Actually, looking at the `Task` example (https://github.com/Ni55aN/d3-node-editor/wiki/Extras) I think, maybe it might be a solution? I mean, instead of "signals" from the keyboard it could be signals from my "repeater" node? Just trigger `task.run()` for every entity thus starting next node. Will it work, in your opinion? 
And I'm just not sure I understand how to use the `Task`. Am I right, once the `Task` is introduced all the following nodes in a chain also must be "task-driven", right? So won't be able to write just `outputs[0] = someData` for any node placed after the task-driven node, it always must be either `task.option()` or `task.output()`, right?

Will be really appreciated for any advice/hints
Thanks!

**Comment by Ni55aN** [comment]
The nodes are processed according to an algorithm in which each node is processed only once. That is, according to the Data flow, they can not be processed otherwise.

> The only confusing thing is that error handling would be harder to implement
Why? Probably, at processing node many times there can be problems, as it will complicate processing

> maybe it might be a solution
Perhaps I did not have to use Task for this purpose. They are meant for delayed processing of nodes on demand from outside, but in no way depend on the data that they process.

I think if you give an array, then it needs to be processed together in order to avoid problems in the future. Moreover, data flow does not imply such interactions
