### ISSUE TITLE
Zoom-in bug.

### ISSUE THREAD

**Issue by Trashtalk217** [Ni55aN/d3-node-editor#68]
This might be trivial or just a problem with the demo, but there is definetly some weird zooming behaviour going on.

## Steps to reproduce:
- Load the first demo: https://codepen.io/Ni55aN/pen/jBEKBQ
- Zoom out as far as you can.
- Drag the a component (or all of them) to the far left (or right).

Now it's impossible to zoom-in on the components placed on the far left/right. You also can't drag yourself over to the components when zoomed in. The only way to interact (or fix) it is by zooming out again and moving the components back to the middle.

P.S. Would you like me to create an issue for spelling mistakes in the code. (Please say no, I don't like to be a grammer Nazi)

**Comment by Ni55aN** [comment]
Ok, I'll try to fix this by limiting the movement of nodes

> Would you like me to create an issue for spelling mistakes in the code.

Good idea. I'll be glad to get help with it

**Comment by Ni55aN** [comment]
3741c462c6b4a62fdaf99447cac2c5a232e385ba
