### ISSUE TITLE
Multiple reference errors on clean install

### ISSUE THREAD

**Issue by MagnificRogue** [Ni55aN/d3-node-editor#69]
Hello! Thanks for making such an awesome project. I'm looking to integrate it with something i'm building and i'm finding that a simple 

`import * as D3NE from "d3-node-editor";`
results in reference errors for the `alight` package and calls to `d3-zoom`. Playing around a little bit, I can manually add the calls to import alight and d3 to the corresponding modules that error out, running build in the package, and things eventually stop yielding errors but the displayed components are broken. 

In general, I'm wondering what the expected behavior should be from an npm install and import.

**Comment by Ni55aN** [comment]
Hello!
Dependencies "d3" and "alight" must be imported globally. 
It depends on the build system that you are using. For example, there is not the most correct way:
```js
import * as d3 from 'd3';
import * as alight from 'alight';
window.d3 = d3;
window.alight = alight;
```

I'm still going to build the library so that you do not have to import the dependencies separately

**Comment by MagnificRogue** [comment]
Where would you look toward adding that? If it's not too complicated I can work toward a PR.

**Comment by Ni55aN** [comment]
What kind of build system do you use?
Webpack - use ProvidePlugin
Angular - [global scripts](https://github.com/angular/angular-cli/wiki/stories-global-scripts)

> If it's not too complicated I can work toward a PR.

cool!

**Comment by MagnificRogue** [comment]
I'm building my project with webpack personally, but I feel as though if I am putting time into solving this problem I would be better off trying to solve the problem in the most general case instead of just my project :smile:

**Comment by Ni55aN** [comment]
I'll try to build a library with external peer dependencies to solve this problem as soon as I have free time

Perhaps this will help https://rollupjs.org/guide/en - Peer dependencies

**Comment by Ni55aN** [comment]
Now it's enough just to install and import D3NE
Example: https://github.com/Ni55aN/D3NE-examples/tree/master/Angular

**Comment by MagnificRogue** [comment]
:heart:  You beat me to the punch!
