### ISSUE TITLE
can i use d3-node-editor with phaser framework

### ISSUE THREAD

**Issue by Turkm** [Ni55aN/d3-node-editor#70]
can i use d3-node-editor with phaser framework(https://phaser.io/), if yes i would appreciate if there an example.

and thanks for the great work.

**Comment by Ni55aN** [comment]
I'm not sure, but I'll try to prepare an example.
In fact, the library can work wherever HTML and JS work

**Comment by Turkm** [comment]
realy appreciate your work, i tried to figure it out but i couldn't, and thank you for the quick answer.

**Comment by Ni55aN** [comment]
Phaser draws on canvas, so the solution is to overlay the D3NE container over canvas

https://github.com/Ni55aN/D3NE-examples/tree/master/Phaser

**Comment by Turkm** [comment]
thanks for your replay but what i meant is how to embed phaser functionality with D3NE so we could make games using phaser with D3NE,

![capture](https://user-images.githubusercontent.com/9050403/38489447-1b0a7456-3bef-11e8-904e-a5ca53b532d3.PNG)

**Comment by Ni55aN** [comment]
@Turkm how do you run the example?

So you want to create visual editor for creating Phaser based games? It is difficult to describe so simply. It is necessary to take a look at the objects which contains the Phaser engine and on their basis create nodes that will manipulate these objects according to the data-flow

**Comment by Turkm** [comment]
hi Ni55an, 
1 - npm i
2 - npm run build
then i tried both the index files in (dist, src) in firefox, chrom and nothing appeared in browser instead i got an errors:

Index, dist, forefox:
![dist forsfox](https://user-images.githubusercontent.com/9050403/38607513-884e5fe4-3d81-11e8-8116-40ef52de18cd.PNG)

index, src, firefox:
![src firfox](https://user-images.githubusercontent.com/9050403/38607543-9a53b48c-3d81-11e8-921e-9cba77fdf0d5.PNG)

index, dist, chrome:
![dist chrom](https://user-images.githubusercontent.com/9050403/38607573-b364b804-3d81-11e8-8dee-11678bf7a951.PNG)

index, src, chrome:
![src chrom](https://user-images.githubusercontent.com/9050403/38607613-c9f4b98e-3d81-11e8-8c17-a6ee535492d0.PNG)

so is it possible to embed phaser functionality with D3NE as you did with your example (allmatter)?

**Comment by Ni55aN** [comment]
Just rechecked and it works:

```
npm i
npm run build
```
Then I run the application via `http-server dist`.
You can try `npm run dev`

![2018-04-12 00-30-54](https://user-images.githubusercontent.com/8259641/38644338-d9c0c832-3de8-11e8-9413-53577c56835e.png)

`

**Comment by Ni55aN** [comment]
> so is it possible to embed phaser functionality with D3NE as you did with your example (allmatter)?

Yes sure, you can create editor. But you must have experience with Phaser to know what should be 
 nodes and data.
