### ISSUE TITLE
Can't search for categories

### ISSUE THREAD

**Issue by Trashtalk217** [Ni55aN/d3-node-editor#71]
When I try to find a category in the search menu it doesn't show up, it only shows results of the components themselve.

## How to recreate the bug
- Open once again https://codepen.io/Ni55aN/pen/jBEKBQ.
- Left-click on the white background to bring up the menu.
- Type in the word 'Values' in the search bar and you'll find it doesn't show up.

This probably isn't a major bug to solve but it'll get tricky when looking for submenus inside of submenus, but I'm sure you'll be able to figure it out.

P.S. When just typing in Value, it doesn't directly show the component Value, but it shows the submenu which leads to 'Value'. I don't know if this is by design but it would be a lot easier if you were taken straight to the actual component.

**Comment by Ni55aN** [comment]
d655676668f9e439d95caa551f73569529010b9e
