### ISSUE TITLE
Listeners

### ISSUE THREAD

**Issue by Hamdiovish** [Ni55aN/d3-node-editor#72]
I think it is important to have listeners in many components at some levels, for example a listener when a node is about to be deleted, so developers can free up some ressources associated with that node, or show some alerts, save some data etc.

**Comment by Ni55aN** [comment]
Something like that?
```js
new D3NE.Component('mycomp', {
    builder(node){ },
    worker(node, inputs, outputs){ },
    created(node){ }.
    destroyed(node){ }
});
```
I think this can be represented as a node's lifecycle (as it is in Vue.js for components)

**Comment by Hamdiovish** [comment]
Yes exactly like that!
Component's lifecycle feature will give the ability to the library to be used in complex and heavy usages such websocket or whatever.

**Comment by Ni55aN** [comment]
4085c9e72d087371240025e8a5f6a3d8cb8a2b39

**Comment by Hamdiovish** [comment]
You're an Artist man,
Perfect job, 
I'm interested in contributing in this project, please consider to comment its code, its main components and build instructions for easier contribution.

Keep up the good work

**Comment by Ni55aN** [comment]
Thanks! I'll do it in the near future

**Comment by Ni55aN** [comment]
https://github.com/retejs/lifecycle-plugin
