### ISSUE TITLE
Regenerator-Runtime Crash

### ISSUE THREAD

**Issue by racaban** [Ni55aN/d3-node-editor#73]
When I create an environment in which regenerator-runtime is installed, the exports for the d3-node-editor are not the expected object, containing the Component, ContextMenu, etc. Instead, it seems to be an object related to the async fetch of that object - 

> D3NE: {wrap: ƒ, isGeneratorFunction: ƒ, mark: ƒ, awrap: ƒ, AsyncIterator: ƒ, …}

This, in turn, causes the sample code to crash when executed...

> TypeError: __WEBPACK_IMPORTED_MODULE_3_d3_node_editor__.Socket is not a constructor

As a temporary solution, I was able to stop this code from occurring by removing all references to regenerator-rumtime, but this includes needed babel-core packages. Alternatively, modifying the compiled code also corrected the issue.

### node_modules/d3-node-editor/build/d3-node-editor.js
```
  var runtime = global.regeneratorRuntime;
-  if (runtime) {
+  if (runtime && false) {
```

Recreated by creating a new package with the `vue create`, modifying the App.vue to include the sample code given at https://codepen.io/Ni55aN/pen/jBEKBQ. 

### App.vue
```
<template>
	<div id="nodeEditor" class="node-editor"></div>
</template>

<script>
import * as D3NE from 'd3-node-editor';
window.D3NE = D3NE;

export default {
  name: "App",
  mounted() {
/* Javascript from sample goes here */
  },
}
</script>
```

Alternatively, in a webpack environment install the regenerator-runtime package (not verified).

**Comment by Ni55aN** [comment]
Can you share a live example?
