### ISSUE TITLE
Node truncating long text

### ISSUE THREAD

**Issue by MagnificRogue** [Ni55aN/d3-node-editor#74]
Problem: Components with long titles, or inputs/outputs with long titles have that information truncated:
![image](https://user-images.githubusercontent.com/7548646/38519730-6d680c1a-3c06-11e8-975e-0ba40b14f3fc.png)
Solution: Setting node width to be `auto`:
![image](https://user-images.githubusercontent.com/7548646/38519839-ab829e66-3c06-11e8-9107-88eaa76cf635.png)

This can be changed in either the client application by overriding the style with the `node` class or in the project's [index.sass](https://github.com/Ni55aN/d3-node-editor/blob/master/src/styles/index.sass) file (and removed from the [vars.sass](https://github.com/Ni55aN/d3-node-editor/blob/master/src/styles/vars.sass) file). Is there a particular reason it's hard coded to 180 px that isn't obvious?  If not, let me know so I can make a PR.

**Comment by Ni55aN** [comment]
The title can be wrapped to a new line:
![opera _2018-04-09_233043_localhost](https://user-images.githubusercontent.com/8259641/38521438-5a8ee0a8-3c4e-11e8-8ba6-9166bd220a62.png)

Usually long titles contain spaces, then the text will be moved to a new line.

In any case, I will make the auto width and min-width: 180px

**Comment by Ni55aN** [comment]
670660b5f620bd4cff67d7aabf7010a180a3d3f9
