### ISSUE TITLE
Module Documentation

### ISSUE THREAD

**Issue by MagnificRogue** [Ni55aN/d3-node-editor#75]
On the documentation page for the [Engine](https://github.com/Ni55aN/d3-node-editor/wiki/Engine), there is a link to the documentation for modules that is broken. In addition, there doesn't appear to be any documentation regarding modules in the wiki.

**Comment by Ni55aN** [comment]
Thank you, I will try to find time for this

**Comment by MagnificRogue** [comment]
Is there a way that documentation can be tracked and generated from the repo? I wouldn't mind expanding it but I don't really know how to do that without wiki access.

**Comment by Ni55aN** [comment]
You can "Clone this wiki locally", make changes and push git. But before that I should give you access for editing the Wiki, adding you as a Collaborator. How do you think?

Perhaps it will need to use the documentation generators and store it on Github Pages

**Comment by MagnificRogue** [comment]
Thanks for pointing that out. Doing a little bit of research it seems like there's not an official workflow for making pull requests to wiki's. An interesting idea that I saw was someone cloning the wiki, making changes, and then raising an issue with a link to the new proposed documentation (along with the set of changes) and a maintainer merging it into the wiki. Do you think that might be a good way? 

I also think that there might be some necessity to using Github Pages, but I'm sure we can get to that eventually. As for adding me as a Collaborator, I don't think that's necessary for the kind of changes I'm thinking about (and I prefer a pull-request, review, merge workflow personally :stuck_out_tongue: )

**Comment by Ni55aN** [comment]
> Do you think that might be a good way?

I do not think it looks easy enough. Perhaps it is better to create a separate branch for documentation in the form of .md files or better use .html (received from a generator) and display it as Github Pages. The main task is to choose a generator, as previously I did not have to use them for such purposes

>  like some overkill in this case.

Yeah, it can take a lot of time

**Comment by MagnificRogue** [comment]
[This blog post](https://blog.github.com/2016-08-22-publish-your-project-documentation-with-github-pages/) might be the best thing to get started. Here the only overhead would be creating a docs folder, copying the current wiki state into the folder, and making some slight configuration for the page. 

Another really good option might be to integrate with [Read The Docs](https://docs.readthedocs.io/en/latest/) which would be free and require a webhook.

**Comment by Ni55aN** [comment]
Read The Docs looks good. I'll try it

**Comment by Ni55aN** [comment]
Wiki's .md transfered to [readthedocs](http://d3-node-editor.readthedocs.io/)

Source .md are available in `docs/` folder

**Comment by Ni55aN** [comment]
I think it would be better if the documentation commits will contains a prefix [docs]

**Comment by MagnificRogue** [comment]
Agreed, do you think that kind of idea could be added to the [contributing](https://github.com/Ni55aN/d3-node-editor/blob/master/CONTRIBUTING.md) guidelines?

**Comment by Ni55aN** [comment]
Yeah

**Comment by Ni55aN** [comment]
https://github.com/Ni55aN/d3-node-editor/blob/master/CONTRIBUTING.md
