### ISSUE TITLE
Namespace removed from d3-node-editor/src/index.d.ts

### ISSUE THREAD

**Issue by mikecowgill** [Ni55aN/d3-node-editor#76]
Is there a reason the namespace was removed from the typescript definition after v0.6.10?

I'm using in angular and after updating it caused missing namespace errors for D3NE.

**Comment by Ni55aN** [comment]
Do you use
```js
/// <reference path="../../../node_modules/d3-node-editor/src/index.d.ts"/>
```
?

Try simply `import * as D3NE from "d3-node-editor";` and TS will import `index.d.ts` under the specified namespace

**Comment by Ni55aN** [comment]
https://github.com/Ni55aN/D3NE-examples/commit/5a7071052a2e8321c97d8a3ab1394643e685cf47

**Comment by mikecowgill** [comment]
Ah! Yes, importing it with the alias fixes that issue. 
Having additional webpack related issues due to the changes but I'll troubleshoot before asking.

**Comment by Ni55aN** [comment]
Is the problem solved? Can I close the issue?
