### ISSUE TITLE
Run the worker on nodejs

### ISSUE THREAD

**Issue by ALPEEN** [Ni55aN/d3-node-editor#77]
Are there a quick way to import the library in nodejs as a module?
And is it possible to write the worker code only once and run it in the frontend but also in the backend via nodejs?
Thank you in advance

**Comment by Ni55aN** [comment]
Yeah, the Engine can work in any JS environment. You only need components with workers.

I'll prepare example.

**Comment by Ni55aN** [comment]
Currently library cannot be imported in node because dependencies use browser's DOM. 
I'll prepare solution and example

**Comment by Ni55aN** [comment]
v0.7.1 is available. So you can use Engine as follows:
```js
var { Engine, ComponentWorker } = require('d3-node-editor/build/d3-node-editor.engine');

var c1 = new ComponentWorker('component1', {
    worker(node, inputs, outputs) {
        console.log('worker')
        outputs[0] = 1;
    }
});

var engine = new Engine('name@0.0.0', [c1]);

engine.process({
    id: 'name@0.0.0',
    nodes: {
        1: {
            title: 'component1',
            id: 1,
            inputs: [],
            outputs: []
        }
    },
    groups: { }
}).then(console.log)
```

[Example](https://github.com/Ni55aN/D3NE-examples/tree/master/nodejs)

**Comment by ALPEEN** [comment]
As wanderful as quick, i will test it and come back with my feedback.
Thank you very very much

**Comment by ALPEEN** [comment]
It did the job, but comparing to the basic working mode of the library there is a fondamental issue.
In the full version, the one with the UI, the schema remain live and respend to any change in any input and run the engine again.
While for the engine of the nodejs version, the engine works only once and cannot interract with the input change, the input can be changed via an external call per example or programatically.
So i think the solution is to keep the engine live, why not in a thread.

**Comment by ALPEEN** [comment]
The main needs for this scenario is to be able to run the schema made by the user without the forcing him to let his computer open.
Per example in the case of a chat bot, when a company create a chat bot for its website, it need to deploy it somewhere and just leave chrome.
There are so many serious use cases for running the graph offline, which will enlarge the usage of the library.

**Comment by Ni55aN** [comment]
Well, you are able to send data from editor.toJSON() to server and process them when you want on the server.

**Comment by ALPEEN** [comment]
I'll try to explain more, lets take the [Flow-based programming](https://codepen.io/Ni55aN/pen/jBEKBQ), what if one of the input was coming from a dynamic node running a websocket or webservices call or reading from a database.
**In the GUI mode:** The window will remain active and the Add component will recalculate the sum of every new coming data.
**In the backend mode:** Currently, the engin running in the server cannot satisfy this recuirement.
To overpass this limitation, we have to implement the logic of the dynamic node separetly, then we have to re execute the engine for every new coming data.
This trick can work but its against the logic of the library, the perfect solution will be to run the engine in a continious process, like it was in an active window, so the engine remain live and can respond to any external data changes of its nodes, this way we can have exactly the same bahavour for the **GUI mode** and the **Backend mode**.
What do you think of such feature?

**Comment by Ni55aN** [comment]
> input was coming from a dynamic node

In what sense node is the dynamic? Node's worker can obtain data from the server, as it supports asynchronous operations.

> we have to re execute the engine for every new coming data.

Exactly, in the case of a backend, it can be caused by a client request for a specific route (created by express.js, for example)

> run the engine in a continious process

The `engine.process()` is called when it is necessary, but it does not work "continuously" (In the case of the client side, when the graph is changed)

Can you describe the principle of what you want in the UML sequence diagram or something similar?
