### ISSUE TITLE
Accessing the Editor from the Component

### ISSUE THREAD

**Issue by ALPEEN** [Ni55aN/d3-node-editor#78]
Hi man,
Refering to this [example](https://codepen.io/Ni55aN/pen/jBEKBQ) and to the documentation, the only way to access the Editor is to use a global object, which is not the best  way to do since its against the moduling and structuration of the code.
For example, i'am working with AngularJS, i created a service to manage the B3NE stuff then i create the Editor in the controller, but i'm obliged to link the editor to the window object to be able to access it within the scope of the service.
A node is a part of an Editor, child parent relationship, so it must be a way to access its Editor and communicate with other nodes.

The same for the Engine, there are lot of cases when nodes need to call its engine to abort or to restart.

Regards

**Comment by Ni55aN** [comment]
It depends on your environment. For example, you can use eventbus or state storage to manage this.

There are many situations in which you may need access to the editor. In the variant suggested by you, it can only work if you access the instance of the node in the builder, but not in the worker (`node` argument is not an instance).

Perhaps I can help you if you provide an example of your code

**Comment by ALPEEN** [comment]
I finished by using a global object and it works well.
Many thanks
