### ISSUE TITLE
can I some-have skip the alight dependency?

### ISSUE THREAD

**Issue by trsh** [Ni55aN/d3-node-editor#81]
For what is it used?

**Comment by trsh** [comment]
My project is already on Ang5, so.. another 64 KB

**Comment by Ni55aN** [comment]
In addition, I do not think that 64 KB. it's a lot. 
D3js weighs in much more, like Angular himself

**Comment by Ni55aN** [comment]
Moreover, you can do a lazy loading of component with the editor and its dependencies

**Comment by trsh** [comment]
@Ni55aN OK clear.

**Comment by trsh** [comment]
Do not have a lot of choice. Googled like mad and only lightweight alternative is https://github.com/shamansir/rpd, but the project seems abandoned.
