### ISSUE TITLE
sockets as option

### ISSUE THREAD

**Issue by Flippo24** [Ni55aN/d3-node-editor#82]
As Idea:
Make sockets optional. For example, whe i like to add 1 to an value i need to connect only the varaible an then there could be an textbox for the second fixed value.  So i dont need an extra node for a fixed value. If a value in the textbox is set, then the socket could be hidden.

As well make it possible to extend the number of input sockets in the editor, if they have the same type. Like your add block, the inputs are integer. If i like to add 5 values i need more blocks in a row. But all 5 could connected to only one add block.

**Comment by Flippo24** [comment]
The extra Control is what i thougt of. Thanks for that.

For the multiple imputs, the idea was to set it in the editor not in code. Like a Block can be resized and when a place for the next input will be big enought to show the input, then the input should be automatically added with the same type. I know it from some PLC programming software.

**Comment by Ni55aN** [comment]
Check out this: https://jsfiddle.net/Ni55aN/c6ts0y2j/

It works, but there may be problems with import/export (`fromJSON()`)

**Comment by Flippo24** [comment]
Cool! Thanks for your work.
