### ISSUE TITLE
drag & drop node connecting as option?

### ISSUE THREAD

**Issue by trsh** [Ni55aN/d3-node-editor#83]
In a lot of node editors (for example Blender3D nodes), you have to drag connection to sockets. So people might start with that intuitively. But when actually doing it, it look very bugous. 

It also could solve the problem: "How to get rid of a connection started". Right now I have to click somewhere on screen to cancel connection, and that doesn't work 100%.  Sometimes I get stuck with a started connection and can get it lost only by refreshing screen.

**Comment by Ni55aN** [comment]
Blender's node editor doesn't allow to zoom & translate with picked connection. User must hold the mouse button while dragging. It is inconvenient in terms of UX for long distance connections. IMHO

We can vote "Do we have to replace the method with the one proposed?"

- Yes :+1: 
- Don't care :confused: 
- No :angry:

**Comment by trsh** [comment]
@Ni55aN don't replace, but as an option :)

**Comment by ALPEEN** [comment]
I think its okay for the current implementation, no need for dragging the connection, but why not as an option.
But regarding to blender, it has a too important option in term of UX, which is the ability to drop a node on top of a path of a connection, then, the node set in the middle of that path, of course if the in/out sockets match the other side's sockets.
I worked a lo with blender and it's realy an example to follow!

**Comment by trsh** [comment]
The point is, than when you click on Socket, don't release mouse and drag, it looks ugly and bugous.

**Comment by trsh** [comment]
I'm for both methods!

**Comment by Ni55aN** [comment]
I give up, ahah. Take it! 

Left the old behavior and added a drag & drop
48a8c10bd43a5aa08ec2505959f9ab4c78a9d086

**Comment by trsh** [comment]
@Ni55aN cool, tnx, will test this soon.
