### ISSUE TITLE
Please add `connection` to editor.view.connectionProducer params (or bind it)

### ISSUE THREAD

**Issue by trsh** [Ni55aN/d3-node-editor#85]
Because I would really like to change the curve depending on node (connections -> output & input). And product different line styles for different connections.

**Comment by trsh** [comment]
Thank you ;). Do you accept PR's?

**Comment by Ni55aN** [comment]
Yes, if they satisfy the code style and have a simple solution

**Comment by trsh** [comment]
@Ni55aN please check PR :)
