### ISSUE TITLE
contextmenu.show coords

### ISSUE THREAD

**Issue by JMidd91** [Ni55aN/d3-node-editor#87]
Hello,

firstly sorry if im posting this in the wrong place, I have only just made a github account.

this isnt really an issue, more of a request - 

so i am using your d3ne and its contained within another div. 

currently from what i understand, when you click on the div the context menu gets created in a new div attached to the body. so if the node editor is nested, you wont see the menu (or thats the result i found)

i had to go into your library and change it from body, to the node editors parent div. 

also aside from that, you place the context menu at the page / client xy coords, which is fine if the node editor is the only thing on screen ( no parent div ) but in my case, the menu appears with a massive offset as its using screen coords rather than local coords. so again i went in to your library and changed page / client xy to layer xy instead.

is there any reason why these changes shouldnt be included? 

sorry if any of this doesnt make sense, im typing this instead of going to bed haha

thanks for taking the time to read this :)

**Comment by Ni55aN** [comment]
Hello!

> if the node editor is nested, you wont see the menu 

can you prepare example? 

>  which is fine if the node editor is the only thing on screen ( no parent div ) but in my case,

Oddly, I placed the editor into container and changed the location on the page, but the menu is still displayed under the cursor

**Comment by JMidd91** [comment]
[example.zip](https://github.com/Ni55aN/d3-node-editor/files/1977526/example.zip)
here is a zip of an example of what i was trying to set up,

firstly youll see that the context menu is created on the body and not the nested window so it doesnt show up. then when that is sorted youll see the context window isnt appearing on mouse coords. i have included the d3-node-editor.js file that i have edited and called it d3-node-editor_edited.js so you can compare the two and see the changes i  have made.

I hope that makes sense?

**Comment by Ni55aN** [comment]
@JMidd91 the problem is related to the z-index property.
#layout_mainWindow_panel_preview has `z-index: 120` and .w2ui-panel-content has `z-index: 1`. They overlay the context menu.
Try to define
```css
.context-menu {
    z-index: 130;
}
```

**Comment by JMidd91** [comment]
Oh ok awesome. Will give that a try when I'm home next
