### ISSUE TITLE
Cannot import the "ComponentWorker" in Nodejs side with TypeScript

### ISSUE THREAD

**Issue by ALPEEN** [Ni55aN/d3-node-editor#88]
Unable to import the "ComponentWorker" when working on the server side, nodejs, using TypeScript:

Getting the following error when importing via "import * as D3NE  from 'd3-node-editor';" :
` Error: ⨯ Unable to compile TypeScript
src/index.ts (14,42): Property 'ComponentWorker' does not exist on type 'typeof "/workspaces/eclipse/botox/node_modules/d3-node-editor/src/index"'. (2339)`

and the following error when importing via "import * as D3NE  from 'd3-node-editor/d3-node-editor.engine';" :
`TSError: ⨯ Unable to compile TypeScript
src/index.ts (6,24): Cannot find module 'd3-node-editor/d3-node-editor.engine'. (2307)`

and the following error when importing via "import { ComponentWorker}  from 'd3-node-editor';" :
`src/index.ts (14,37): 'ComponentWorker' only refers to a type, but is being used as a value here. (2693)`

I googled the issue and checked the sources of the libs, i think its related to exporting stuff for TS of the "ComponentWorker".

**Comment by Ni55aN** [comment]
9e12e6f8971e58cfedbe5f99d77700ced0345043

**Comment by ALPEEN** [comment]
Worked!
But there is a new extra param "name" in the interface "ComponentWorkerProps":
`interface ComponentWorkerProps {
name : string;
 worker: ComponentWorkerFunc;
}`

So the ComponentWorker must be:
`var c1 = new ComponentWorker('component1', {
    name : "what is it for?",
    worker(node, inputs, outputs) {
        console.log('worker')
        outputs[0] = 1;
    }
});`

Otherwise, there will be an error:
`TSError: ⨯ Unable to compile TypeScript
src/index.ts (3,44): Argument of type '{ worker(node: any, inputs: any[][], outputs: any[]): void; }' is not assignable to parameter of type 'ComponentWorkerProps'.
`

**Comment by Ni55aN** [comment]
Oops, I made a mistake

**Comment by Ni55aN** [comment]
e062494e6f06fa556becb60062791dcefe1899e2

**Comment by ALPEEN** [comment]
Perfect!
Thank you man
