### ISSUE TITLE
Overkill in drawing paths

### ISSUE THREAD

**Issue by trsh** [Ni55aN/d3-node-editor#96]
https://codepen.io/anon/pen/ELbowE?editors=1010

Open console and find line with console.log

U can see, that even no path is being changed (dragged orsmth), the even fires and feeds the Path draw function. These are lot's of calculations for nothing? On a weaker PC it's actually creating micro-lags.

We should only redraw path, that is being dragged /& changed. And redraw all on pan or zoom, etc.

**Comment by Ni55aN** [comment]
The `update()` method is called on the mousemove event to update the active connection that follows the mouse cursor.

Anyway, I plan to rewrite some part of the library and get rid of the dependencies D3 and Alight. Although there will be more vanilla JS code, but there will be more control over performance

**Comment by trsh** [comment]
> The update() method is called on the mousemove event to update the active connection that follows the mouse cursor.

Yeah I understood that. But it doesn't check if a connection is active (being dragged). It just fires on every mouse move and thereby processes all connections, even if you are doing like nothing. Just playing with your mouse or some other work.

About the Alight part:

I suggest to look into micro fast frameworks, like https://github.com/adamhaile/surplus (< 15kb not gziped, 5 gziped with all features), for templating. As I suspect, that rolling your own solution for this part can get: a) never ending story b) slow c) probably even more Kilobytes d) limitations in templating and processing them e) some alien code for custom templates. People are working for years on such frameworks to get them small and fast and still they aren't perfect, so do not underestimate this area, please.  

PS I'm not saying surplus is best candidate, but it's speed is close to vanilla so it remarkable. A bit hard to learn in my opinion :P

**Comment by Ni55aN** [comment]
> I suggest to look into micro fast frameworks

I think that vanilla JS-code will not be much more than using such a library. Moreover, rendering templates (view, context menu, nodes) is not necessary, since some of this will be rendered in the form of plugins and with the choice of various libraries (React, Vue)
